version: '3.4'

services:
  umbracoondocker:
    build:
      context: .
      dockerfile: UmbracoOnDocker/Dockerfile
    ports:
      - "33380:80"
      - "33381:443"
    depends_on:
      - mydb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__umbracoDbDSN=Server=mydb,1433;Database=UmbracoDocker;User Id=sa;Password={YourStrongPassword};TrustServerCertificate=true;
  mydb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "{YourStrongPassword}"
      ACCEPT_EULA: "Y"
    ports:
      - "34700:1433"
    volumes:
      - ../data:/var/opt/mssql/data:rw
